# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

plugins:
  - jekyll-paginate
  #- jekyll-redirect-from

# Setup
title:            'OSCAR Computer Algebra System'
tagline:          ''
description:      'The OSCAR project'
location:         ''
url:              http://sebasguts.github.io
baseurl:          /oscar-website/


exclude: [ "LICENSE.hyde.md", "README.hyde.md" ]
include: [ ]
